In [121]:
from os import listdir, makedirs
from os.path import isfile, isdir, join

import numpy as np
import pandas as pd

flare_file_path = './output/joined_flares.csv'
merged_sharp_path = '../new-data-loc/'
output_merged_sharp_path = '../annotated-new-data/'

noaa_map_path = './all_harps_with_noaa_ars.txt'
noaa_map = False  # global variable
downloads_noaa_map = False # global variable

from flare_reader import get_flare_dataframe
from aia_flare_integration import get_aia_flare_dataframe, get_goes_flare_dataframe
fdf = get_flare_dataframe(flare_file_path)

In [123]:
#Check if there are any long flares
fdf['goes_class'][(fdf['end_time'] - fdf['start_time']) > '8 hours'].head()

Series([], Name: goes_class, dtype: object)

In [124]:
# fdf['goes_class'][(fdf['peak_time_aia'] - fdf['peak_time_goes']) > '30 minutes'].head()

a = fdf[ np.abs(fdf['peak_time_aia'] - fdf['peak_time_goes']) > '40 minutes']
np.abs(a['peak_time_aia'] - a['peak_time_goes'])
# a

Empty DataFrame
Columns: [end_time, event_date, goes_class, aia_location, goes_location, id_aia, id_goes, noaa_active_region_aia, noaa_active_region_goes, peak_time_aia, peak_time_goes, start_time, noaa_active_region, fl_location, fl_lat, fl_lon, peak_time]
Index: []

In [93]:
goes_fl_file_path = './allFlares.txt'
goes_fl = get_goes_flare_dataframe(goes_fl_file_path)
# goes_fl[['goes_class', 'event_date']][(goes_fl['end_time'] <= goes_fl['peak_time'])]
goes_fl[(goes_fl['peak_time'] < goes_fl['start_time'])]

,end_time,event_date,goes_class,goes_location,noaa_active_region,peak_time,start_time,id_goes
1625,2011-04-12 00:03:00,2011-04-11,C2.5,"(-25, 12)",11190,2011-04-11,2011-04-11 23:40:00,1626
3571,2012-04-06 00:05:00,2012-04-05,C1.1,"(0, 0)",11450,2012-04-05,2012-04-05 23:50:00,3572
3978,2012-06-07 00:05:00,2012-06-06,C1.0,"(6, -19)",11494,2012-06-06,2012-06-06 23:56:00,3979
4396,2012-07-31 00:04:00,2012-07-30,C6.3,"(0, 0)",11538,2012-07-30,2012-07-30 23:50:00,4397
4863,2012-10-14 00:18:00,2012-10-13,C1.5,"(-25, 11)",11589,2012-10-13,2012-10-13 23:46:00,4864
8375,2014-05-26 00:04:00,2014-05-25,C3.8,"(73, -17)",12065,2014-05-25,2014-05-25 23:49:00,8376
13203,2017-03-27 00:08:00,2017-03-26,C1.3,"(-33, 12)",12644,2017-03-26,2017-03-26 23:49:00,13204

In [81]:
goes_fl[(goes_fl['end_time'] < goes_fl['start_time'])] #-> this looks good

Empty DataFrame
Columns: [end_time, event_date, goes_class, goes_location, noaa_active_region, peak_time, start_time, id_goes]
Index: []

In [82]:
goes_fl[(goes_fl['end_time'] < goes_fl['peak_time'])] #-> this looks good

Empty DataFrame
Columns: [end_time, event_date, goes_class, goes_location, noaa_active_region, peak_time, start_time, id_goes]
Index: []

In [120]:
goes_fl[(goes_fl['end_time'] - goes_fl['start_time']) > '6 hours']

,end_time,event_date,goes_class,goes_location,noaa_active_region,peak_time,start_time,id_goes
127,2010-07-06 03:12:00,2010-07-05,B1.2,"(0, 0)",0,2010-07-06 00:24:00,2010-07-05 18:36:00,128
4329,2012-07-17 19:04:00,2012-07-17,M1.7,"(65, -28)",11520,2012-07-17 17:15:00,2012-07-17 12:03:00,4330
4803,2012-10-05 10:46:00,2012-10-05,B7.8,"(0, 0)",11584,2012-10-05 07:30:00,2012-10-05 03:17:00,4804
5586,2013-02-25 15:40:00,2013-02-25,B8.9,"(0, 0)",11678,2013-02-25 11:51:00,2013-02-25 05:15:00,5587
12148,2016-04-10 13:04:00,2016-04-10,C1.5,"(0, 0)",12529,2016-04-10 09:34:00,2016-04-10 05:49:00,12149
12840,2016-10-15 15:29:00,2016-10-15,B2.6,"(0, 0)",0,2016-10-15 14:10:00,2016-10-15 08:33:00,12841
13556,2017-06-28 18:35:00,2017-06-28,B1.3,"(0, 0)",12664,2017-06-28 15:24:00,2017-06-28 12:27:00,13557

In [94]:
from aia_flare_integration import get_aia_flare_dataframe, get_goes_flare_dataframe

aia_fl_file_path = './aiaFlares.txt'
aia_fl = get_aia_flare_dataframe(aia_fl_file_path)
aia_fl[(aia_fl['peak_time'] < aia_fl['start_time'])]

,event_date,start_time,end_time,goes_class,goes_location,noaa_active_region,peak_time,id_aia
1660,2011-05-19,2011-05-19 03:45:00,2011-05-19 05:15:00,B2.0,POINT(33 18),0,2011-05-18 16:37:00,1661

In [79]:
aia_fl[(aia_fl['end_time'] < aia_fl['start_time'])] #-> this is null so we are good

Empty DataFrame
Columns: [event_date, start_time, end_time, goes_class, goes_location, noaa_active_region, peak_time, id_aia]
Index: []

In [80]:
aia_fl[(aia_fl['end_time'] < aia_fl['peak_time'])] #-> this is null so we are good

Empty DataFrame
Columns: [event_date, start_time, end_time, goes_class, goes_location, noaa_active_region, peak_time, id_aia]
Index: []

In [119]:
aia_fl[(aia_fl['end_time'] - aia_fl['start_time']) > '6 hours']

,event_date,start_time,end_time,goes_class,goes_location,noaa_active_region,peak_time,id_aia
133,2010-07-02,2010-07-02 18:15:00,2010-07-03 02:45:00,A6.4,POINT(59 -25),1085,2010-07-02 21:47:00,134
136,2010-07-05,2010-07-05 18:36:00,2010-07-06 03:12:00,B1.2,POINT(54 18),1086,2010-07-06 00:24:00,137
153,2010-07-10,2010-07-10 03:47:00,2010-07-10 10:23:00,B5.2,POINT(-60 16),1087,2010-07-10 06:30:00,154
464,2010-10-10,2010-10-10 19:00:00,2010-10-11 01:30:00,A9.4,POINT(-33 -15),0,2010-10-10 20:03:00,465
769,2010-12-06,2010-12-06 14:00:00,2010-12-07 04:00:00,B2.3,POINT(-19 -19),0,2010-12-07 00:22:00,770
1995,2011-07-25,2011-07-25 12:34:00,2011-07-26 00:05:00,B4.2,POINT(-71 19),0,2011-07-25 12:48:00,1996
4130,2012-05-25,2012-05-25 12:53:00,2012-05-26 13:25:00,B7.2,POINT(-86 -10),1490,2012-05-25 13:10:00,4131
4452,2012-07-17,2012-07-17 12:03:00,2012-07-17 19:04:00,M1.7,POINT(88 -15),1519,2012-07-17 17:15:00,4453
5207,2013-02-25,2013-02-25 05:15:00,2013-02-25 15:40:00,B8.9,POINT(-43 -28),1680,2013-02-25 11:51:00,5208
6406,2014-01-20,2014-01-20 21:40:00,2014-02-07 00:15:28,C3.7,POINT(-71 -9),0,2014-01-20 22:49:00,6407
6921,2014-03-24,2014-03-24 00:04:00,2014-03-24 22:24:00,C4.5,POINT(-25 -11),2014,2014-03-24 00:10:00,6922
7302,2014-06-26,2014-06-26 21:01:00,2014-06-27 05:00:00,C1.7,POINT(-89 13),2100,2014-06-27 00:58:00,7303
10383,2015-11-11,2015-11-11 13:30:00,2015-11-11 20:45:00,B8.1,POINT(21 2),2451,2015-11-11 17:34:00,10384
10471,2015-12-16,2015-12-16 13:45:00,2015-12-16 20:15:00,B7.3,POINT(6 -17),2468,2015-12-16 17:15:00,10472
10521,2015-12-24,2015-12-24 03:42:00,2015-12-25 08:00:00,C5.9,POINT(-50 5),2472,2015-12-24 06:16:00,10522
11342,2016-07-05,2016-07-05 19:10:00,2016-07-06 02:30:00,B3.7,POINT(37 19),0,2016-07-05 21:47:00,11343
11727,2016-10-15,2016-10-15 08:33:00,2016-10-15 15:29:00,B2.6,POINT(87 -17),2599,2016-10-15 14:10:00,11728
12506,2017-06-28,2017-06-28 12:27:00,2017-06-28 18:35:00,B1.3,POINT(24 20),2664,2017-06-28 15:24:00,12507
12641,2017-07-20,2017-07-20 19:20:00,2017-07-21 01:55:00,B1.7,POINT(89 -7),2665,2017-07-20 23:15:00,12642